<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <Version>1.2.0</Version>
    <Deterministic>true</Deterministic>
    <UseSharedCompilation>false</UseSharedCompilation>
  </PropertyGroup>
</Project>
